// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcdSGYcqXuNokOgHVdhsf5nx9QDvXS9cM',
    appId: '1:807333810653:web:b82b27fa94e601eac72634',
    messagingSenderId: '807333810653',
    projectId: 'ipar-2ea1c',
    authDomain: 'ipar-2ea1c.firebaseapp.com',
    storageBucket: 'ipar-2ea1c.appspot.com',
    measurementId: 'G-5HFLPMZZPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiL1qsjuz6Oevh2NgW2bZDDMyJ7lHaNag',
    appId: '1:807333810653:android:b881d372ad89de1bc72634',
    messagingSenderId: '807333810653',
    projectId: 'ipar-2ea1c',
    storageBucket: 'ipar-2ea1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaPQjbrl2dqMnavp6YzD-zrviwnisVPH4',
    appId: '1:807333810653:ios:b305edb274e0f0c1c72634',
    messagingSenderId: '807333810653',
    projectId: 'ipar-2ea1c',
    storageBucket: 'ipar-2ea1c.appspot.com',
    iosBundleId: 'com.example.iparcompany',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaPQjbrl2dqMnavp6YzD-zrviwnisVPH4',
    appId: '1:807333810653:ios:c048912111e132c7c72634',
    messagingSenderId: '807333810653',
    projectId: 'ipar-2ea1c',
    storageBucket: 'ipar-2ea1c.appspot.com',
    iosBundleId: 'com.example.iparcompany.RunnerTests',
  );
}
