// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpbkc4jSJU5JLRitqt23nRt5ByZ1bXZCw',
    appId: '1:118133458855:web:07cf98561d576325529882',
    messagingSenderId: '118133458855',
    projectId: 'medg-735d8',
    authDomain: 'medg-735d8.firebaseapp.com',
    storageBucket: 'medg-735d8.appspot.com',
    measurementId: 'G-LLQBYY7QR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWHg-WB_f0ARRXlhkoy2e9mPPiXoYyZM',
    appId: '1:118133458855:android:c97424afad5696de529882',
    messagingSenderId: '118133458855',
    projectId: 'medg-735d8',
    storageBucket: 'medg-735d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA41lz_olPrJBZqURjpLwXyWPqhiTCMxs',
    appId: '1:118133458855:ios:8e18cf36f3f17ca2529882',
    messagingSenderId: '118133458855',
    projectId: 'medg-735d8',
    storageBucket: 'medg-735d8.appspot.com',
    iosBundleId: 'com.example.med',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA41lz_olPrJBZqURjpLwXyWPqhiTCMxs',
    appId: '1:118133458855:ios:7b4a5440766830e9529882',
    messagingSenderId: '118133458855',
    projectId: 'medg-735d8',
    storageBucket: 'medg-735d8.appspot.com',
    iosBundleId: 'com.example.med.RunnerTests',
  );
}
